;; Test: arithmetics
;; Description:
;    Simple arithmetics test. Printing the results so they can be compared.

;; add
2 2 +                print
10 1 + 2 +           print
2 3 + 5 + 3 +        print
2 2 -                print
25 3 - 9 -           print
50 10 - 20 - 3 - 4 - print
2 3 *                print
2 2 * 2 *            print
2 2 2 2 2 * * * *    print
10 2 /               print
;; BUG: multiple division together like 32 2 2 2 / / / fail.
;; 32 2 2 2 / / /    print ;; 4
32 2 / 2 / 2 /       print
3 4 + 7 + 1 -        print
10 5 / 3 + 5 * 12 -  print
