10 3 + print
20 7 - print
neg 10 23 + print
13 1 * print
neg 13 neg 1 * print
1337 100 / print
2 3 + dup dup dup * * * print
;; -5 -3 - 2 - print ;; -4
;; TODO: Fix the above case where the result should be -4, but instead is -1.
;; The reason due to this being -1 is that it's leaving the -5 on the stack and doing
;; the actual substraction with -3 and -2. So -3 - -2 = -1. The real operation should
;; be -5 - -3 = -2, and then -2 - 2 = -4.
