;; Test: arithmetics
;; Description:
;    Simple arithmetics test. Printing the results so they can be compared.

2 2 +                print ; 4
10 1 + 2 +           print ; 13
2 3 + 5 + 3 +        print ; 13
2 2 -                print ; 0
25 3 - 9 -           print ; 13
50 10 - 20 - 3 - 4 - print ; 13
2 3 *                print ; 6
2 2 * 2 *            print ; 8
2 2 2 2 2 * * * *    print ; 32
10 2 /               print ; 5
32 2 2 2 / / /       print ; 16 (32 2 2 2 / / / -> 32 2 1 / / -> 32 2 / -> 16)
32 2 / 2 / 2 /       print ; 4
10 3 %               print ; 1
3 4 + 7 + 1 -        print ; 13
10 5 / 3 + 5 * 12 -  print ; 13
