proc fibonacci-recursive (int --- int)
  dup 2 < if else dup 1 - fibonacci-recursive swap 2 - fibonacci-recursive + fi
;

proc fibonacci-loop (int --- int)
  var n0 0 ;
  var n1 1 ;
  var n2 1 ;

  3 swap 1 + ..< for
    n1 'n0 set
    n2 'n1 set
    n0 n1 + 'n2 set
  loop

  n2
;

proc main
  1 fibonacci-recursive print
  2 fibonacci-recursive print
  3 fibonacci-recursive print
  4 fibonacci-recursive print
  5 fibonacci-recursive print
  6 fibonacci-recursive print
  7 fibonacci-recursive print

  1 fibonacci-loop      print
  2 fibonacci-loop      print
  3 fibonacci-loop      print
  4 fibonacci-loop      print
  5 fibonacci-loop      print
  6 fibonacci-loop      print
  7 fibonacci-loop      print
;
