using "io"

;; Test: arithmetics
;; Description:
;    Simple arithmetics test. Printing the results so they can be compared.

function main do
  "2 + 2 = 4  "   print
  2 2 +           println
  "-----------"   println

  "10 + 1 + 2 = 13  " print
  10 1 + 2 +          println
  "-----------"       println

  "2 + 3 + 5 + 3 = 13  " print
  2 3 + 5 + 3 +          println
  "-----------"          println

  "2 - 2 = 0  "   print
  2 2 -           println
  "-----------"   println

  "25 - 3 - 9 = 13  "  print
  25 3 - 9 -           println
  "-----------"        println

  "50 - 10 - 20 - 3 - 4 = 13  " print
  50 10 - 20 - 3 - 4 -          println
  "-----------"                 println

  "2 * 3 = 6  "   print
  2 3 *           println
  "-----------"   println

  "2 * 2 * 2 = 8  " print
  2 2 * 2 *         println
  "-----------"     println

  "2 * 2 * 2 * 2 * 2 = 32  " print
  2 2 2 2 2 * * * *          println
  "-----------"              println

  "10 / 2 = 5  "  print
  10 2 /          println
  "-----------"   println

  "32 / (2 / 2 / 2) = 16  " print
  32 2 2 2 / / /            println
  "-----------"             println

  "((32 / 2) / 2) / 2 = 4  " print
  32 2 / 2 / 2 /             println
  "-----------"              println

  "10 % 3 = 1  "  print
  10 3 %          println
  "-----------"   println

  "3 + 4 + 7 - 1 = 13  " print
  3 4 + 7 + 1 -          println
  "-----------"          println

  "10 / 5 + 3 * 5 - 12 = 13  " print
  10 5 / 3 + 5 * 12 -          println
  "-----------"                println

  "10 ++ ++ ++ ++ -- = 13  " print
  10 ++ ++ ++ ++ --          println
.
