foreign proc printf (string any) --- ;

proc print-string (string)
  "%s" swap printf
;

proc print-bool (bool)
  "%d\n" swap printf
;

proc main
  "equal\n" print-string
  "2 2 = -> true " print-string 2 2 = print-bool
  "2 3 = -> false " print-string 2 3 = print-bool
  "3 2 = -> false " print-string 3 2 = print-bool
  "test test -> true " print-string "test" "test" = print-bool
  "test Test -> false " print-string "test" "Test" = print-bool
  "-----------\n" print-string

  "not equal\n" print-string
  "2 3 != -> true " print-string 2 3 != print-bool
  "3 2 != -> true " print-string 3 2 != print-bool
  "2 2 != -> false " print-string 2 2 != print-bool
  "test Test -> true " print-string "test" "Test" != print-bool
  "test test -> false " print-string "test" "test" != print-bool
  "-----------\n" print-string

  "less\n" print-string
  "3 2 > -> true " print-string 3 2 > print-bool
  "2 3 > -> false " print-string 2 3 > print-bool
  "3 3 > -> false " print-string 3 3 > print-bool
  "-----------\n" print-string

  "less equal\n" print-string
  "3 3 >= -> true " print-string 3 3 >= print-bool
  "3 2 >= -> true " print-string 3 2 >= print-bool
  "2 3 >= -> false " print-string 2 3 >= print-bool
  "-----------\n" print-string

  "greater\n" print-string
  "2 3 < -> true " print-string 2 3 < print-bool
  "3 2 < -> false " print-string 3 2 < print-bool
  "2 2 < -> false " print-string 2 2 < print-bool
  "-----------\n" print-string

  "greater equal\n" print-string
  "2 2 <= -> true " print-string 2 2 <= print-bool
  "2 3 <= -> true " print-string 2 3 <= print-bool
  "3 2 <= -> false " print-string 3 2 <= print-bool
;
