const a 10 5 + ;
const b 2.14 1. + ;
const c 1000 10 % ;
const d 1340 3 - ;
const e 10 3 * ;
const f 1024 8 / ;
const g c ;
const h int c  1 + ;
const i uint 127u ;
const j 128u i + ;
const k string "Stańczyk" ;

fn main
  const x "internal constant" ;

  "15  " print a println
  "3.14  " print b println
  "0  " print c println
  "1337  " print d println
  "30  " print e println
  "128  " print f println
  "0  " print g println
  "1  " print h println
  "127  " print i println
  "255  " print j println
  "Stańczyk  " print k println
  "internal constant  " print x println

  const a "shadowing" ;
  "shadowing  " print a println
;
