using io

;; Test: constants
;; Description:
;    making sure consts are evaluated correctly

const thirty 30
const string "String constant"
const booleanTrue true
const booleanFalse false

fn main ()
	const twenty 20
  const local "local"

  "30  " print thirty println
  "String constant  " print string println
  "true  " print booleanTrue println
  "false  " print booleanFalse println

	"20  " print twenty println
  "local  " print local println

  const booleanTrue false
  "false  " print booleanTrue println
ret
