const a 10 5 + ;
const c 1000 10 % ;
const d 1340 3 - ;
const e 10 3 * ;
const f 1024 8 / ;
const g c ;
const h int c  1 + ;
const i uint 127u ;
const j 128u i + ;
const k string "Stańczyk" ;

proc main
  const x "internal constant" ;

  "15  "                print a print
  "0  "                 print c print
  "1337  "              print d print
  "30  "                print e print
  "128  "               print f print
  "0  "                 print g print
  "1  "                 print h print
  "127  "               print i print
  "255  "               print j print
  "Stańczyk  "          print k print
  "internal constant  " print x print

  const a "shadowing" ;
  "shadowing  " print a print
;
