using "io"

;; Test: control-flow
;; Description:
;    Test the control flow mechanism

"if true -> 13  " puts
if true do
  13 print
.
"-----------\n" puts

"if false -> (nothing)\n" puts
if false do
  13 print
.
"-----------\n" puts

"if false else -> 13  " puts
if false do
  31 print
else
  13 print
.
"-----------\n" puts

"loop 0 to 5\n" puts
0 loop dup 5 <= do
  dup print
  ++
. drop
"-----------\n" puts

"loop 0 to 10, skipping even\n" puts
0 loop dup 10 <= do
  if dup 2 % 0 != do
    dup print
  .
  ++
. drop
"-----------\n" puts

"loop 0 to 10, skipping odd\n" puts
0 loop dup 10 <= do
  if dup 2 % 0 = do
    dup print
  .
  ++
. drop
"-----------\n" puts

"loop 10 to 0, skipping every 2 elements\n" puts
10 loop dup 0 >= do
  if dup 3 % 0 = do
    dup print
  .
  --
. drop
"-----------\n" puts
