using io

;; Test: flow-control
;; Description:
;    Test the control flow mechanism

fn main ()
  "if true -> 13  " print
  if true (
    13 println
  )
  "-----------" println

  "if false -> (nothing)" println
  if false (
    13 println
  )
  "-----------" println

  "if false else -> 13  " print
  if false (
    31 println
  else
    13 println
  )
  "-----------" println

  "loop 0 to 5" println
  0 for dup 5 <= (
    dup println
    ++
  ) drop
  "-----------" println

  "loop 0 to 10, skipping even" println
  0 for dup 10 <= (
    if dup 2 % 0 != (
      dup println
    )
    ++
  ) drop
  "-----------" println

  "loop 0 to 10, skipping odd" println
  0 for dup 10 <= (
    if dup 2 % 0 = (
      dup println
    )
    ++
  ) drop
  "-----------" println

  "loop 10 to 0, skipping every 2 elements" println
  10 for dup 0 >= (
    if dup 3 % 0 = (
      dup println
    )
    --
  ) drop
  "-----------" println
ret
