using "io"

function* equal int int -> bool do
  =
.

function* equal bool bool -> bool do
  =
.

function* equal ptr ptr -> bool do
  str=
.

function main do
  "Testing polymorphism with this function that takes different parameters but always returns a boolean value" println
  "true  " print 2 2 equal println
  "false  " print false true equal println
  "true  " print "test" "test" equal println
.
