using io

fn get-str (--- str)
  "My test string"
ret

fn main ()
  "Testing strings in Stańczyk is a little bit more complicated" println

  "Stańczyk" "Stańczyk" strequal if
    "1- test success" println
  else
    "1- test failed!" println
  fi

  get-str get-str strequal if
    "2- test success" println
  else
    "2- test failed!" println
  fi

  "Stańczyk" "Nope" strequal if
    "3- test failed!" println
  else
    "3- test success" println
  fi
ret
