;; A simple variable with value 13.
:= simple-13 13 .
simple-13 print

;; Another simple variable with value 4.
:= not-13 4 .
not-13 print

;; A variable where we evaluate something before setting it.
:= evaluating (13 2 + 3 +) .
evaluating print

;; Setting this variable again, but now it is 13.
= not-13 not-13 9 + .
not-13 print

;; Saving a string
:= this-is "thirdteen" .
this-is print

;; nil value
:= is-nil .
is-nil print
