using io

;; Test: recursion
;; Description:
;    testing recusive functions
const ORIGINAL 10

fn add-3-to-original (int --- int)
  dup ORIGINAL 3 + = if
    leave
  else
    ++ add-3-to-original leave
  fi
ret

fn main ()
  "define a recursive function that adds 3 (1 by 1) to 'ORIGINAL' of value 10 and returns it"
  println
  "add-3-to-original  13  " print
  ORIGINAL add-3-to-original println
ret
